### ISSUE TITLE
Serversided script

### ISSUE THREAD

**Issue by Froster2406** [p410n3/knifechoose.nut#1]
Would it be possible to make the script work on a server?

As it stands right now, the vscript works for all users with the default knife enabled but only with the hardcoded standard-knife (flip).

Froster

**Comment by p410n3** [comment]
How do you have it set up right now?

**Comment by Froster2406** [comment]
I just exec the whole vscript on each round start

**Comment by p410n3** [comment]
Well I need more info. Is it a dedicated server in the server browser? Does it run plugins? Is it just you hosting the server?

Technically if you can exec the script with 
    script_execute kc

You dont have to exec it every round. You have to use the command

    script knifeSetup()

And to chnage the knifes 

    script knifeSelectNext()
    script knifeSelectPrev()

**Comment by Froster2406** [comment]
The server is hosted locally on my backup windows-pc (windows 10).

- Sourcemod 1.9 - build 6275
- Metamod 1.10 - build 968

Installed are the following Plugins:
- Retakes v0.3.4 by Splewis
- convar weapon allocator v0.2.0 by BatMen
- Instadefuse v1.2.1 by Jacoblairm
- Autoplanter 1.3.0 by Technoblazed
- Randomcycle

I will try to implement it as you showed above.

**Comment by p410n3** [comment]
> The server is hosted locally on my backup windows-pc (windows 10).
> 
> * Sourcemod 1.9 - build 6275
> * Metamod 1.10 - build 968
> 
> Installed are the following Plugins:
> 
> * Retakes v0.3.4 by Splewis
> * convar weapon allocator v0.2.0 by BatMen
> * Instadefuse v1.2.1 by Jacoblairm
> * Autoplanter 1.3.0 by Technoblazed
> * Randomcycle
> 
> I will try to implement it as you showed above.

Please write back when you tried.

**Comment by SergeyKasmy** [comment]
Why would you use this script when it is only intended for local servers with no access to sourcemod? There are other full blown plugins that can achieve what you want. The ones that Valve banned, they are still updated and you can still use them(on your own risk, of course, but If the server isn't advertised over/easily accessed from the net, you should be okay). This whole script is one big workaround I created for bot practice when I sold my old knife and felt uncomfortable without it. 

Maybe try something [like this](https://github.com/Franc1sco/Franug-Knifes). I found it in 10 seconds in Google, if it doesn't work you can search a bit more

**Comment by Froster2406** [comment]
> The ones that **Valve banned**, they are still updated and you can still use them

Thats the exact reason I choose this option and not a SM plugin. I could also use a GSLT-Token service, but I am not really a fan of it.

**Comment by p410n3** [comment]
> > The ones that **Valve banned**, they are still updated and you can still use them
> 
> Thats the exact reason I choose this option and not a SM plugin. I could also use a GSLT-Token service, but I am not really a fan of it.

IIRC they are getting banned from the server browser, not generally banned (how even). Use a non advertised server then. 

If you want this script to "bypass" the rule valve made, dont. 

The rule isnt banning specific plugins but rather the practice of giving players skins that would normally be obtained with money.

So it will still be a violation of that rule regardless.

**Comment by p410n3** [comment]
Closed due to lack of new Info
