### ISSUE TITLE
Add weapon_knife_css

### ISSUE THREAD

**Issue by sjain882** [p410n3/knifechoose.nut#2]
Hey there,

This knife model got added today in the new update.

https://blog.counter-strike.net/index.php/2019/10/25894/

Thanks so much in advance. Hope you're doing well!

**Comment by SergeyKasmy** [comment]
Done

**Comment by sjain882** [comment]
Christ, within an hour, just like the Shiv, well done, thanks so much

**Comment by SergeyKasmy** [comment]
It's all good, I was just doing my stuff on the PC and it was kinda a nobrainer to add these two or something lines. Some time ago I rewrote the script to be more modular for a reason after all :)
