### ISSUE TITLE
New Operation update broke script?

### ISSUE THREAD

**Issue by st0le** [p410n3/knifechoose.nut#3]
Script isn't working for me? I was trying to add new knives. Can someone else confirm?

**Comment by st0le** [comment]
Nevermind. I messed up my copy

**Comment by psknayak** [comment]
Hey I have an issue with it as well. When I try running the script through console, it says "Error. Index kc_ not found" . Tried replacing the file multiple times. No luck

**Comment by st0le** [comment]
I suggest you start a new issue with more details

**Comment by SergeyKasmy** [comment]
> Hey I have an issue with it as well. When I try running the script through console, it says "Error. Index kc_ not found" . Tried replacing the file multiple times. No luck

I fixed the crash in the last update, sorry!
