### ISSUE TITLE
Execute cl_fullupdate after script is loaded.

### ISSUE THREAD

**Issue by st0le** [p410n3/knifechoose.nut#5]
Can we execute cl_fullupdate after the Timer is setup? The console log keeps getting spammed until this command is executed (on my machine atleast)

**Comment by SergeyKasmy** [comment]
I've never heard of this command, gonna look into it, thanks for the heads up

**Comment by SergeyKasmy** [comment]
I honestly still don't understand what exactly cl_fullupdate does but it requires sv_cheats and I don't wan't to enable cheats, even for a moment

**Comment by SergeyKasmy** [comment]
Closing since the script was completely rewritten from scratch

**Comment by st0le** [comment]
Awesome. Will try it out today.
