### ISSUE TITLE
Script fails to load in-game (17th September 2020)

### ISSUE THREAD

**Issue by sjain882** [p410n3/knifechoose.nut#7]
It just returns `kc.nut line = (77) column = (9) : error expected '.'` in console.

It seems there is a space where this column is: `Knife <- `, and maybe something is meant to be after that space, not sure.

I tried playing around with it a lot but was unable to get the script to work

EDIT 17/09/2020 22:07 UTC: I seemed to have been able to fix the issue. Created a pull request, details of what it was are there:  https://github.com/p410n3/knifechoose.nut/pull/8

**Comment by p410n3** [comment]
Fixed in https://github.com/p410n3/knifechoose.nut/pull/8
